- hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Install Nginx
      yum: name=nginx state=present

    - name: start nginx
      service: name=nginx state=started

- hosts: team2
  become: true
  become_user: root
  tasks:
    - name: stop nginx container
      service: name=nginx state=stopped

